name: MCSLT
channels:
  - defaults
  - r
  - pytorch
  - conda-forge
dependencies:
  - scipy
  - seaborn
  - rpy2
  - pandas
  - matplotlib
  - numpy
  - python
  - jupyter
  - tzlocal
  - pywavelets
  - pandas-datareader
  - cudatoolkit
  - torchaudio
  - pytorch
  - torchvision
  - pyro-ppl
  - gpytorch
  - statsmodels
  - networkx
  - python-igraph
  - graphviz